version: '3.9'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./main-service
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./main-service:/usr/src/app

  event:
    build:
      dockerfile: Dockerfile
      context: ./event-service
      target: dev
    volumes:
      - ./event-service:/usr/src/app

  model:
    build:
      dockerfile: Dockerfile
      context: ./power-prediction-service
    ports:
      - 8001:8001


  front-end:
    build: 
      dockerfile: Dockerfile
      context: ./front-end
    ports:
      - 5173:5173
    volumes:
      - ./front-end:/usr/src/app
  
  # nodered:
  #   image: nodered/node-red:3.1.0-18
  #   container_name: nodered
  #   privileged: true
  #   environment:
  #     - TZ=Europe/Rome
  #   restart: unless-stopped
  #   volumes:
  #     - ./simulator:/data
  #   ports:
  #     - 1880:1880
  
  importer:
    build:
      dockerfile: Dockerfile
      context: ./importer
      target: dev
    volumes:
      - ./importer:/usr/src/app
    