var version = '2'

export const pvInfoEndpoint = '/api/v' + version + '/pvinfo'
export const pvDataEndpoint = '/api/v' + version + '/pvdata'
export const wsInfoEndpoint = '/api/v' + version + '/wsinfo'
export const wsDataEndpoint = '/api/v' + version + '/wsdata'
export const usersEndpoint = '/api/v' + version + '/users'
export const meEndpoint = '/api/v' + version + '/users/me'
export const authEndpoint = '/api/v' + version + '/users/authentication'
export const refreshEndpoint = '/api/v' + version + '/users/refresh'
export const productionReportsEndpoint = '/api/v' + version + '/reports/production'
export const moneyReportsEndpoint = '/api/v' + version + '/reports/money'
export const pvnumberReportsEndpoint = '/api/v' + version + '/reports/pvnumber'
